version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./maison-darin-backend
      dockerfile: Dockerfile
    container_name: maison-darin-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://maisondarin:pjSZYpFRahUTeB81@cluster0.yanlxkn.mongodb.net/maison-darin?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=maison-darin-super-secure-jwt-secret-production-2024
      - JWT_REFRESH_SECRET=maison-darin-refresh-secret-production-2024
      - CLOUDINARY_CLOUD_NAME=dbixjzxgp
      - CLOUDINARY_API_KEY=541661697753599
      - CLOUDINARY_API_SECRET=nBlJQPoCISYrdFu2YR6GlDtKskU
      - FRONTEND_URL=https://maisondarin.com
      - EMAIL_APP_PASSWORD=cnzs qjfg mxzg pkmb
      - SMTP_USER=maisondarin2025@gmail.com
      - SMTP_PASS=cnzs qjfg mxzg pkmb
      - ADMIN_EMAIL=maisondarin2025@gmail.com
    volumes:
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    networks:
      - maison-darin-network
    healthcheck:
      test: ["CMD", "node", "scripts/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ./maison-darin-luxury-beauty
      dockerfile: Dockerfile
    container_name: maison-darin-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - maison-darin-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Cache Service (Optional)
  redis:
    image: redis:7-alpine
    container_name: maison-darin-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis-password-2024
    volumes:
      - redis_data:/data
    networks:
      - maison-darin-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional - for SSL termination)
  nginx-proxy:
    image: nginx:alpine
    container_name: maison-darin-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    networks:
      - maison-darin-network
    profiles:
      - with-ssl

volumes:
  backend_logs:
    driver: local
  backend_uploads:
    driver: local
  redis_data:
    driver: local

networks:
  maison-darin-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
